### PR TITLE
all sprites in images/pokemon, pokemon show up in map

### PR DESCRIPTION
**Pull request by kcgilland143**

### CODE REVIEW

**Comment by bowenbrinegar** [comment]
Just seeing this, if we could set up a Google hangout to talk through how we can apply this to the current master, that would be great. It currently has no merge conflicts because it is changing the app.js which we are no longer using.

And is this connected to the render function? If not, I think it will require a change in how we interact with the database, though not sure. Thoughts?

**Comment by bowenbrinegar** [comment]
And this is an obvious benefit of the render function.

**Comment by kcgilland143** [comment]
This isn't connected to the render function at all, I can definitely get this working in the new organized version. It changes the way we interact with the Pokemon api a little bit. I'm still getting my bearings on how the new files operate.

**Comment by bowenbrinegar** [comment]
Want to google hangout?

**Comment by bowenbrinegar** [comment]
If not tonight, in the morning? Id really like to get on the same page.

**Comment by kcgilland143** [comment]
Can't tonight, busy day tomorrow, but we can definitely get back on the same track.

**Comment by bowenbrinegar** [comment]
Let me know when you can connect.

**Comment by kcgilland143** [comment]
You still available? If not, see ya early tomorrow!

**Comment by bowenbrinegar** [comment]
See you in the morning!

**Comment by kcgilland143** [comment]
Going to close this pull request

**Pull request closed without merging**
