### PR TITLE
updated fixes/ready for next steps

### PR DESCRIPTION
**Pull request by bowenbrinegar**
Kevin, I hope you saw my comment on the last one, still down to google hangout tonight. You too Jane, we have it in a working state and it's ready for some updates on the design front.

In commit: variable additions, styling width on pokemonCollection, isotope remove prepended, and loading pokemon upon user creation

### CODE REVIEW

**Comment by kcgilland143** [comment]
this is good stuff! only thing is, with the way the isotope and pouch is being handled, it's god awful slow, and doesn't have that cool transition anymore

**Comment by bowenbrinegar** [comment]
Minor flaws worth trading off for a functional website that works dynamically and with the database. We can address these issues once we have a real MVP. We need to move on. We've got to have a running version so Jane can start adding her stuff. So I'm going to merge this branch with your approval, because the flaws your talking about were in the last merge. If you want to work through a render function that dynamically adapts to different UI needs, thats okay, but you need to consider the battle mode, the pouch, and the response modals to catching a pokemon, lossing your pokemon, and failing to catch the pokemon (which have yet to be created). All will require different CSS and data application. Please get back to this message so Jane can start in the morning

**Comment by bowenbrinegar** [comment]
I've also updated the Google Docs with new and more detailed ideas of areas that would be progress to work on. Please give your input.

**Comment by bowenbrinegar** [comment]
Is this good to go? We can change how the previous merge operates later on, but this merge doesn't have any major changes. It just fixes problems with the last merge

**Comment by kcgilland143** [comment]
That's fine. I have a few questions about the codebase and it's current state, I didn't realize at first how much of the code you changed while reorganizing, basically making it impossible for me to find and fix bugs , some of which I've already fixed multiple times. Moving forward, I'll just add features we need and button up the site, just adapting to the style you've written it in.

**Comment by bowenbrinegar** [comment]
I feel like i'm doing the same, i think we need to utlize google hangouts more. Im sorry for the problems i've caused on your end.

**Comment by kcgilland143** [comment]
For sure. sorry I bailed on our plans yesterday, had something unexpected
come up. We can later today, it would be nice to touch base before Saturday

**Comment by bowenbrinegar** [comment]
Yeah, lets do it, i'm open anytime after 5.

**Pull request merged**
