### PR TITLE
Markers to Firebase/Modal Additions

### PR DESCRIPTION
**Pull request by bowenbrinegar**
Changed how we store markers and reference them

### CODE REVIEW

**Comment by bowenbrinegar** [comment]
This commit will add the modals as well, so I can close my previous pull request.

**Review by kcgilland143 — CHANGES_REQUESTED** [review]
I have reviewed the code, not tested, as far as the marker logic goes, it's very concise! I very much enjoyed reading the code.
The first two commits add the modal, the last three are marker/firebase. the two branches should be separated. 
You can reset the modal changes with the command
git checkout origin/master assets/javascript/config.js index.html assets/javascript/variables.js assets/javascript/login.js assets/css/style.css  assets/javascript/battle.js
in your working directory, then, you just need to add the bracket to markers object>>array.
There is also a way to revert the specific commits, but i'm not sure
I've tested this, and it seems to work properly. it does throw an error, but the only thing that causes is pokemon to not popup before user is logged in, we can call that a feature

**Comment by bowenbrinegar** [comment]
I don't see the point in doing two different branches at this point, the changes I've implement are simple and have no conflicts and do not alter the existing code. Consider this the modal branch, with 5 extra lines of reference changes. And it needs to be an array.

**Review by kcgilland143 — APPROVED** [review]

**Comment by kcgilland143** [comment]
The changes work fine and everything works as intended when merged. being that you've already removed the other branch, I guess there is no longer a point to separate them again. Approved

**Pull request merged**
