### PR TITLE
Locationfinder

### PR DESCRIPTION
**Pull request by bowenbrinegar**
Haven't solved this piece yet, I put the button in to call on the function of the location finder and whats need to reposition the places, but going through the documentation (https://developers.google.com/maps/documentation/javascript/3.exp/reference#LatLngBounds), it doesn't seem to be working the way we want it to.

another link to check out
(https://www.w3.org/TR/2016/REC-geolocation-API-20161108/)

and the buttons are clicking a little off of their location, not sure why, but click around each button to get it to work

### CODE REVIEW

**Comment by kcgilland143** [comment]
The work is nice! it is just not ready for merging yet, and includes the changes from the first pull request, I am working on this issue, we should continue work on this branch before merge

**Comment by bowenbrinegar** [comment]
Alright, I went ahead with merging the first pull request. Continue on the "locationfinder" branch!

**Comment by bowenbrinegar** [comment]
It's looking great! We need to make the Pokemon show up less so i'm going to lower the radius. I think we can get rid of one of the buttons too. Then we can move on to the next step. I'm going to do a small commit, if your good with it, I'll merge.

**Comment by kcgilland143** [comment]
Sounds good, I was experimenting with lowering the amount, the radius helps a little, but using less gplaces seems to be the way to go

**Comment by bowenbrinegar** [comment]
Agreed, minor problem, lowering the radius make the reappearance of places that have already been clicked on stand out.

**Review by kcgilland143 — COMMENTED** [review]
a lot of these changes seem better suited for the style/fixes branch

**Comment by bowenbrinegar** [comment]
agreed, new to the whole branches thing, can we leave these here and remember that for next time?

**Comment by kcgilland143** [comment]
for sure, we're learning. excited to see what it looks like all together anyway.

**Pull request merged**
